before:
  hooks:
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  # https://github.com/fastly/cli/blob/main/.goreleaser.yml
  - <<: &build_defaults
      main: ./
      ldflags:
        - -s -w -X "github.com/FaceChainTeam/go-to-deb/main.Version=v{{ .Version }}"
        - -X "github.com/FaceChainTeam/go-to-deb/main.GitCommit={{ .ShortCommit }}"
        - -X "github.com/FaceChainTeam/go-to-deb/main.Environment=release"
    binary: test-foo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 6
      - 7 
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: linux
        goarch: amd64
nfpms:
  -
    maintainer: Alex Howarth <alex.howarth@gmail.com>
    license: "MIT"
    formats:
      - deb
      - rpm
    overrides:
    contents:
    - src: debian/conf/test-foo.conf
      dst: /etc/test-foo.conf
      type: config
    - src: debian/scripts/systemd/test-foo.service
      dst: /etc/systemd/system/test-foo.service
    scripts:
      postinstall: debian/scripts/postinstall.sh
      preremove: debian/scripts/preremove.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
